Repository sadanandpai/frontend-mini-challenges, pull requests merged in 2023-10, with the labels that each got.

#84 Added a Classic Brick Breaker Game for Javascript Challenges
  native/helpers/challenges.js
  native/machine-coding/brick_breaker/README.md
  native/machine-coding/brick_breaker/brick.png
  native/machine-coding/brick_breaker/index.html
  native/machine-coding/brick_breaker/script.js
  native/machine-coding/brick_breaker/styles.css
Labels: hacktoberfest-accepted

#87 Added a Tilting Maze Game Javascript Challenge
  native/helpers/challenges.js
  native/machine-coding/tilting-maze/index.html
  native/machine-coding/tilting-maze/script.js
  native/machine-coding/tilting-maze/styles.css
  native/machine-coding/tilting-maze/walls.js
Labels: hacktoberfest-accepted

#187 Add Finance Tracker Website
  native/helpers/challenges.js
  native/machine-coding/Finance Tracker/Finance Tracker.png
  native/machine-coding/Finance Tracker/README.md
  native/machine-coding/Finance Tracker/index.html
  native/machine-coding/Finance Tracker/index.js
  native/machine-coding/Finance Tracker/style.css
Labels: changes-requested

#184 Added currency converter
  native/helpers/challenges.js
  native/machine-coding/currency-converter/README.md
  native/machine-coding/currency-converter/index.html
  native/machine-coding/currency-converter/script.js
  native/machine-coding/currency-converter/style.css
Labels: changes-requested

#177 Add a Dice game #138
  native/helpers/challenges.js
  native/helpers/contributors.js
  native/machine-coding/dice-game/dice.js
  native/machine-coding/dice-game/images/dice1.png
  native/machine-coding/dice-game/images/dice2.png
  native/machine-coding/dice-game/images/dice3.png
  native/machine-coding/dice-game/images/dice4.png
  native/machine-coding/dice-game/images/dice5.png
  native/machine-coding/dice-game/images/dice6.png
  native/machine-coding/dice-game/index.html
  native/machine-coding/dice-game/styles.css
Labels: changes-requested

#238 Create debugforangularinvscode.txt
  angular/.vscode/debugforangularinvscode.txt
Labels: pending-review

#227 Color Mixer
  react/src/helpers/challenges.ts
  react/src/machine-coding/color-mixer/color.module.css
  react/src/machine-coding/color-mixer/index.jsx
  react/src/pages/Challenge.tsx
Labels: changes-requested

#283 rock-paper-scissor added
  native/helpers/challenges.js
  native/machine-coding/rock-paper-scissor/index.css
  native/machine-coding/rock-paper-scissor/index.html
  native/machine-coding/rock-paper-scissor/index.js
  native/machine-coding/rock-paper-scissor/paper.png
  native/machine-coding/rock-paper-scissor/rock.png
  native/machine-coding/rock-paper-scissor/scissors.png
Labels: changes-requested

#291 Your Sport is added
  react/src/helpers/challenges.ts
  react/src/machine-coding/your-sport/index.jsx
  react/src/machine-coding/your-sport/styles.module.css
  react/src/pages/Challenge.tsx
Labels: changes-requested

#279 [Feature Update] Added more questions and select 10 questions randomly.
  native/machine-coding/quiz-app-with-timer/index.js
  native/machine-coding/quiz-app-with-timer/questions.json
Labels: changes-requested

#301 Adding spinning loader
  native/helpers/challenges.js
  native/helpers/contributors.js
  native/machine-coding/spinning-loader/index.html
  native/machine-coding/spinning-loader/styles.css
Labels: changes-requested
